-- 主生产计划表
CREATE TABLE IF NOT EXISTS master_production_plans (
  id INT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
  plan_code VARCHAR(50) NOT NULL UNIQUE COMMENT '主生产计划编号',
  product_code VARCHAR(100) COMMENT '产品编号',
  product_name VARCHAR(200) COMMENT '产品名称',
  order_quantity DECIMAL(15, 4) DEFAULT 0 COMMENT '订单数量',
  salesperson VARCHAR(100) COMMENT '销售员',
  sales_unit VARCHAR(20) COMMENT '销售单位',
  available_stock DECIMAL(15, 4) DEFAULT 0 COMMENT '可用库存',
  current_stock DECIMAL(15, 4) DEFAULT 0 COMMENT '实时库存',
  plan_quantity DECIMAL(15, 4) DEFAULT 0 COMMENT '计划数量',
  product_image VARCHAR(500) COMMENT '产品图片',
  promised_delivery_date DATE COMMENT '订单承诺交期',
  status VARCHAR(50) DEFAULT '已下单' COMMENT '进度状态',
  planned_storage_date DATE COMMENT '计划入库日期',
  product_source VARCHAR(100) COMMENT '产品来源',
  internal_order_no VARCHAR(100) COMMENT '内部销售订单编号',
  customer_order_no VARCHAR(100) COMMENT '客户订单编号',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  INDEX idx_plan_code (plan_code),
  INDEX idx_product_code (product_code),
  INDEX idx_internal_order_no (internal_order_no),
  INDEX idx_status (status),
  INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='主生产计划表';
