-- 创建客户表
CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  customer_code VARCHAR(50) UNIQUE NOT NULL COMMENT '客户编号',
  customer_name VARCHAR(200) NOT NULL COMMENT '客户名称',
  customer_type ENUM('vip', 'regular', 'potential') DEFAULT 'regular' COMMENT '客户类型',
  status ENUM('active', 'lost', 'frozen') DEFAULT 'active' COMMENT '客户状态',
  contact_person VARCHAR(100) COMMENT '联系人',
  contact_phone VARCHAR(50) COMMENT '联系电话',
  contact_email VARCHAR(100) COMMENT '邮箱',
  contact_address TEXT COMMENT '联系地址',
  company VARCHAR(200) COMMENT '公司名称',
  company_address TEXT COMMENT '公司地址',
  industry VARCHAR(100) COMMENT '所属行业',
  region VARCHAR(100) COMMENT '所属区域',
  tax_number VARCHAR(50) COMMENT '税号',
  credit_level ENUM('A', 'B', 'C', 'D') COMMENT '信用等级',
  credit_limit DECIMAL(15,2) DEFAULT 0.00 COMMENT '信用额度',
  used_credit DECIMAL(15,2) DEFAULT 0.00 COMMENT '已用额度',
  total_orders INT DEFAULT 0 COMMENT '订单数量',
  total_amount DECIMAL(15,2) DEFAULT 0.00 COMMENT '累计交易额',
  last_order_date DATE COMMENT '最后下单日期',
  sales_person VARCHAR(100) COMMENT '负责销售',
  source VARCHAR(100) COMMENT '客户来源',
  tags JSON COMMENT '标签',
  remark TEXT COMMENT '备注',
  created_by VARCHAR(50) DEFAULT 'system' COMMENT '创建人',
  updated_by VARCHAR(50) DEFAULT 'system' COMMENT '更新人',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  INDEX idx_customer_code (customer_code),
  INDEX idx_customer_name (customer_name),
  INDEX idx_customer_type (customer_type),
  INDEX idx_status (status),
  INDEX idx_industry (industry),
  INDEX idx_region (region),
  INDEX idx_sales_person (sales_person),
  INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='客户信息表';

-- 插入示例数据
INSERT INTO customers (
  customer_code, customer_name, customer_type, status, contact_person, contact_phone, 
  contact_email, company, industry, region, credit_limit, sales_person, remark
) VALUES 
('CUST202501001', '阿里巴巴集团', 'vip', 'active', '马云', '13800138001', 
 'jack.ma@alibaba.com', '阿里巴巴集团控股有限公司', '互联网', '浙江杭州', 1000000.00, '张销售', 'VIP客户，信用良好'),
('CUST202501002', '腾讯科技', 'vip', 'active', '马化腾', '13800138002', 
 'pony.ma@tencent.com', '深圳市腾讯计算机系统有限公司', '互联网', '广东深圳', 800000.00, '李销售', '战略合作伙伴'),
('CUST202501003', '华为技术', 'regular', 'active', '任正非', '13800138003', 
 'zhengfei.ren@huawei.com', '华为技术有限公司', '通信设备', '广东深圳', 500000.00, '王销售', '重要客户'),
('CUST202501004', '京东集团', 'regular', 'active', '刘强东', '13800138004', 
 'qiangdong.liu@jd.com', '北京京东世纪贸易有限公司', '电子商务', '北京', 600000.00, '赵销售', '长期合作客户'),
('CUST202501005', '百度公司', 'potential', 'active', '李彦宏', '13800138005', 
 'yanhong.li@baidu.com', '百度在线网络技术（北京）有限公司', '互联网', '北京', 200000.00, '钱销售', '潜在客户'),
('CUST202501006', '小米科技', 'regular', 'active', '雷军', '13800138006', 
 'jun.lei@xiaomi.com', '北京小米科技有限责任公司', '智能硬件', '北京', 400000.00, '孙销售', '新兴客户'),
('CUST202501007', '美团点评', 'regular', 'active', '王兴', '13800138007', 
 'xing.wang@meituan.com', '北京三快科技有限公司', '生活服务', '北京', 300000.00, '周销售', '服务类客户'),
('CUST202501008', '字节跳动', 'potential', 'active', '张一鸣', '13800138008', 
 'yiming.zhang@bytedance.com', '北京字节跳动科技有限公司', '互联网', '北京', 150000.00, '吴销售', '潜在VIP客户'),
('CUST202501009', '网易公司', 'regular', 'frozen', '丁磊', '13800138009', 
 'lei.ding@netease.com', '网易（杭州）网络有限公司', '互联网', '浙江杭州', 100000.00, '郑销售', '暂时冻结'),
('CUST202501010', '比亚迪股份', 'vip', 'active', '王传福', '13800138010', 
 'chuanfu.wang@byd.com', '比亚迪股份有限公司', '新能源汽车', '广东深圳', 1200000.00, '冯销售', '新能源行业龙头企业');