-- 创建组装工序计划表
CREATE TABLE IF NOT EXISTS assembly_process_plans (
  id INT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
  plan_no VARCHAR(50) UNIQUE NOT NULL COMMENT '组装工序计划编号',
  schedule_date DATE COMMENT '计划排程日期',
  sales_order_no VARCHAR(50) COMMENT '销售订单编号',
  master_plan_no VARCHAR(50) COMMENT '主生产计划编号',
  shipping_plan_no VARCHAR(50) COMMENT '发货计划编号',
  product_code VARCHAR(50) COMMENT '生产产品编号',
  product_name VARCHAR(200) COMMENT '生产产品名称',
  product_image VARCHAR(500) COMMENT '产品图片',
  process_manager VARCHAR(50) COMMENT '工序负责人',
  process_name VARCHAR(100) COMMENT '工序名称',
  daily_total_hours DECIMAL(10, 2) DEFAULT 0 COMMENT '当天总工时',
  daily_scheduled_hours DECIMAL(10, 2) DEFAULT 0 COMMENT '当天已排程工时',
  daily_available_hours DECIMAL(10, 2) DEFAULT 0 COMMENT '工序当天可用工时',
  schedule_quantity DECIMAL(10, 2) DEFAULT 0 COMMENT '计划排程数量',
  scheduled_work_hours DECIMAL(10, 2) DEFAULT 0 COMMENT '计划排程工时',
  product_unit VARCHAR(20) COMMENT '产品单位',
  level0_demand DECIMAL(10, 2) COMMENT '0阶需求数量',
  completion_date DATE COMMENT '计划完工日期',
  plan_start_date DATE COMMENT '计划开始日期',
  real_plan_start_date DATE COMMENT '真计划开始日期',
  plan_end_date DATE COMMENT '计划结束日期',
  workshop_name VARCHAR(100) COMMENT '车间名称',
  next_schedule_date DATE COMMENT '下一个排程日期',
  schedule_count INT DEFAULT 0 COMMENT '排程次数',
  standard_work_quota DECIMAL(10, 2) COMMENT '定时工额',
  standard_work_hours DECIMAL(10, 2) COMMENT '定额工时',
  required_work_hours DECIMAL(10, 2) DEFAULT 0 COMMENT '需求工时',
  actual_required_work_hours DECIMAL(10, 2) DEFAULT 0 COMMENT '真需求工时',
  remaining_required_hours DECIMAL(10, 2) DEFAULT 0 COMMENT '剩余需求工时',
  cumulative_schedule_qty DECIMAL(10, 2) DEFAULT 0 COMMENT '累积排程数量',
  unscheduled_qty DECIMAL(10, 2) COMMENT '未排数量',
  replenishment_qty DECIMAL(10, 2) COMMENT '需补货数量',
  source_page_name VARCHAR(100) COMMENT '来源页面名称',
  source_no VARCHAR(50) COMMENT '来源编号',
  previous_schedule_no VARCHAR(50) COMMENT '上一个排程单号',
  customer_name VARCHAR(200) COMMENT '客户名称',
  customer_order_no VARCHAR(50) COMMENT '客户订单编号',
  master_plan_product_code VARCHAR(50) COMMENT '主计划产品编号',
  master_plan_product_name VARCHAR(200) COMMENT '主计划产品名称',
  order_promise_delivery_date DATE COMMENT '订单承诺交期',
  level0_product_name VARCHAR(200) COMMENT '0阶产品名称',
  level0_product_code VARCHAR(50) COMMENT '0阶产品编号',
  level0_production_qty DECIMAL(10, 2) COMMENT '0阶主计划生产数量',
  product_source VARCHAR(50) COMMENT '产品来源',
  bom_no VARCHAR(50) COMMENT '生产BOM编号',
  hierarchy_address VARCHAR(100) COMMENT '层阶地址',
  submitted_by VARCHAR(50) COMMENT '提交人',
  submitted_at DATETIME COMMENT '提交时间',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  INDEX idx_plan_no (plan_no),
  INDEX idx_master_plan_no (master_plan_no),
  INDEX idx_process_name (process_name),
  INDEX idx_schedule_date (schedule_date),
  INDEX idx_product_code (product_code),
  INDEX idx_source_no (source_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='组装工序计划表';
